/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-11-14 15:30:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mainpage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Tuk-Team-Gem</title>\r\n");
      out.write("<style>\r\n");
      out.write("        body {  /* body 태그 전체 */\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {  /* header 태그 전체 */\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #333333;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-title {\r\n");
      out.write("            font-size: 2em; /* 페이지 이름을 크게 표시 */\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-left: 30px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        a {  /* a 태그 전체 */\r\n");
      out.write("        	color: inherit; /* 부모 요소의 글자색과 일치 */\r\n");
      out.write("        	text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header a {  /* header 태그 내 a 태그 */\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("		.table-title {\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 1.5em;\r\n");
      out.write("			color: #333333;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("        .container {  /* container 클래스 */\r\n");
      out.write("			width: 80%;\r\n");
      out.write("        	margin: 20px auto;\r\n");
      out.write("        	margin-top: 10px;\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .table-border {\r\n");
      out.write("        	border-radius: 10px;\r\n");
      out.write("        	background-color: #333333;\r\n");
      out.write("        	padding: 1px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {  /* table 태그 전체 */\r\n");
      out.write("  			border-collapse: collapse;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {  /* th, td 태그 전체 */\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {  /* th 태그 전체 */\r\n");
      out.write("            background-color: #333333;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:nth-child(even) {  /* 짝수번째 행일 경우 */\r\n");
      out.write("            background-color: #D6F4FF;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:nth-child(odd) {  /* 홀수번째 행일 경우 */\r\n");
      out.write("            background-color: #F9F9F9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-open {  /* open상태(모집중) 클래스 */\r\n");
      out.write("            color: green;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status-closed {  /* closed상태(모집종료) 클래스 */\r\n");
      out.write("            color: red;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-container {  /* 버튼 정렬을 위한 컨테이너 클래스 */\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            margin: 0px auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-container button {  /* container 클래스 내 button 태그 */\r\n");
      out.write("            margin-right: 20%;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-container button:hover {  /* 버튼에 커서 올렸을 때 */\r\n");
      out.write("            background-color: #0051A8;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .divider {  /* 로그인, 회원가입 구분자를 위한 클래스 */\r\n");
      out.write("    		color: white;\r\n");
      out.write("    		margin-left: 10px;\r\n");
      out.write("    		margin-right: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		nav {  /* 네비게이터 nav 태그 전체 */\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background-color: #007bff;            \r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("        }\r\n");
      out.write("        nav ul {  /* nav 태그 내 ul 태그 */\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"page-title\"><div class=\"\" style=\"color: #0082CC;\">TUK&nbsp;</div>Team Gem</div>\r\n");
      out.write("		<div class=\"account-container\">\r\n");
      out.write("	        <a href=\"#\">로그인</a>\r\n");
      out.write("	        <span class=\"divider\">|</span>\r\n");
      out.write("	        <a href=\"#\" style=\"margin-right: 30px;\">회원가입</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    	<div class=\"table-title\">팀 목록</div>\r\n");
      out.write("    	<hr>\r\n");
      out.write("    	<div class=\"table-border\">\r\n");
      out.write("        	<table>\r\n");
      out.write("	            <thead>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>번호</th>\r\n");
      out.write("	                    <th>제목</th>\r\n");
      out.write("	                    <th>모집 인원</th>\r\n");
      out.write("	                    <th>분야</th>\r\n");
      out.write("	                    <th>마감 여부</th>\r\n");
      out.write("	                    <th>마감일</th>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	            </thead>\r\n");
      out.write("	            <tbody>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <td>3</td>\r\n");
      out.write("	                    <td><a href=\"#\">프로젝트 C</a></td>\r\n");
      out.write("	                    <td>0/5</td>\r\n");
      out.write("	                    <td>백엔드 개발</td>\r\n");
      out.write("	                    <td class=\"status-open\">모집중</td>\r\n");
      out.write("	                    <td>2024.11.12 오후 11:59</td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <td>2</td>\r\n");
      out.write("	                    <td><a href=\"#\">프로젝트 B</a></td>\r\n");
      out.write("	                    <td>4/4</td>\r\n");
      out.write("	                    <td>디자인</td>\r\n");
      out.write("	                    <td class=\"status-closed\">종료</td>\r\n");
      out.write("	                    <td>2024.11.06 오전 2:59</td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <td>1</td>\r\n");
      out.write("	                    <td><a href=\"#\">프로젝트 A</a></td>\r\n");
      out.write("	                    <td>2/3</td>\r\n");
      out.write("	                    <td>임베디드</td>\r\n");
      out.write("	                    <td class=\"status-closed\">종료</td>\r\n");
      out.write("	                    <td>2024.10.30 오후 12:00</td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	            </tbody>\r\n");
      out.write("	        </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"button-container\">\r\n");
      out.write("        <button>모집하기</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 하단 네비게이션 바 -->\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#\">내 팀</a></li>\r\n");
      out.write("            <li><a href=\"#\">홈</a></li>\r\n");
      out.write("            <li><a href=\"#\">지원 현황</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
